services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports: 
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: npm run build_client
    depends_on:
      - server
